"""add attribute system

Revision ID: 58449c36752b
Revises: f8ae547dd094
Create Date: 2026-10-08 00:06:45.046115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58449c36752b'
down_revision: Union[str, Sequence[str], None] = 'f8ae547dd094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('choices', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('group_name', sa.String(length=80), nullable=True),
    sa.Column('is_filterable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_inquiry_option', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(data_type IN ('single_choice', 'multi_choice')) = (choices IS NOT NULL)", name=op.f('ck_attribute_definitions_choices_match_type')),
    sa.CheckConstraint("data_type IN ('text', 'number', 'boolean', 'single_choice', 'multi_choice')", name=op.f('ck_attribute_definitions_data_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribute_definitions')),
    sa.UniqueConstraint('key', name=op.f('uq_attribute_definitions_key'))
    )
    op.create_table('category_attributes',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute_definitions.id'], name=op.f('fk_category_attributes_attribute_id_attribute_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_category_attributes_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'attribute_id', name=op.f('pk_category_attributes'))
    )
    op.create_index(op.f('ix_category_attributes_attribute_id'), 'category_attributes', ['attribute_id'], unique=False)
    op.create_table('product_attribute_values',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.String(length=200), nullable=True),
    sa.Column('value_number', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_choices', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(value_text, value_number, value_bool, value_choices) = 1', name=op.f('ck_product_attribute_values_exactly_one_value')),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute_definitions.id'], name=op.f('fk_product_attribute_values_attribute_id_attribute_definitions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_attribute_values_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'attribute_id', name=op.f('pk_product_attribute_values'))
    )
    op.create_index('ix_product_attribute_values_attr_number', 'product_attribute_values', ['attribute_id', 'value_number'], unique=False)
    op.create_index('ix_product_attribute_values_attr_text', 'product_attribute_values', ['attribute_id', 'value_text'], unique=False)
    op.create_index('ix_product_attribute_values_choices', 'product_attribute_values', ['value_choices'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_attribute_values_choices', table_name='product_attribute_values', postgresql_using='gin')
    op.drop_index('ix_product_attribute_values_attr_text', table_name='product_attribute_values')
    op.drop_index('ix_product_attribute_values_attr_number', table_name='product_attribute_values')
    op.drop_table('product_attribute_values')
    op.drop_index(op.f('ix_category_attributes_attribute_id'), table_name='category_attributes')
    op.drop_table('category_attributes')
    op.drop_table('attribute_definitions')
    # ### end Alembic commands ###
