"""add industries and product highlights

Revision ID: 77bb182daca4
Revises: 84b244b2047c
Create Date: 2026-10-07 23:37:36.634079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77bb182daca4'
down_revision: Union[str, Sequence[str], None] = '84b244b2047c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('seo_title', sa.String(length=160), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('is_placeholder', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name=op.f('ck_industries_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industries')),
    sa.UniqueConstraint('name', name='uq_industries_name')
    )
    op.create_index(op.f('ix_industries_slug'), 'industries', ['slug'], unique=True)
    op.create_table('product_highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.String(length=300), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('feature', 'application')", name=op.f('ck_product_highlights_kind')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_highlights_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_highlights'))
    )
    op.create_index(op.f('ix_product_highlights_product_id'), 'product_highlights', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_highlights_product_id'), table_name='product_highlights')
    op.drop_table('product_highlights')
    op.drop_index(op.f('ix_industries_slug'), table_name='industries')
    op.drop_table('industries')
    # ### end Alembic commands ###
