"""add product industries and related products

Revision ID: e885df8fcf50
Revises: 77bb182daca4
Create Date: 2026-10-07 23:42:49.736431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e885df8fcf50'
down_revision: Union[str, Sequence[str], None] = '77bb182daca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_industries',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('fk_product_industries_industry_id_industries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_industries_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'industry_id', name=op.f('pk_product_industries'))
    )
    op.create_index(op.f('ix_product_industries_industry_id'), 'product_industries', ['industry_id'], unique=False)
    op.create_table('related_products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('related_product_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('product_id <> related_product_id', name=op.f('ck_related_products_no_self_relation')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_related_products_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_product_id'], ['products.id'], name=op.f('fk_related_products_related_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'related_product_id', name=op.f('pk_related_products'))
    )
    op.create_index(op.f('ix_related_products_related_product_id'), 'related_products', ['related_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_related_products_related_product_id'), table_name='related_products')
    op.drop_table('related_products')
    op.drop_index(op.f('ix_product_industries_industry_id'), table_name='product_industries')
    op.drop_table('product_industries')
    # ### end Alembic commands ###
