"""add product listing indexes

Revision ID: f8ae547dd094
Revises: 6ca9f709f9b5
Create Date: 2026-10-07 23:58:06.921751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ae547dd094'
down_revision: Union[str, Sequence[str], None] = '6ca9f709f9b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_products_category_status_sort', 'products', ['category_id', 'status', 'sort_order'], unique=False)
    op.create_index('ix_products_series_id', 'products', ['series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_series_id', table_name='products')
    op.drop_index('ix_products_category_status_sort', table_name='products')
    # ### end Alembic commands ###
